/* 
This code is generated by gtable-generator, do not modify it. 
solopointer1202@gmail.com
*/

#include "log.h"
#include <type_traits>

#include "{{.Name -}}.h"
{{- range $idv, $dv := .Dataviews }}
{{- if $dv.Has_udf }}
#include "{{- $dv.Get_udf }}.h"
{{- end }}
{{- end }}

namespace {{.Namespace}} {

class {{.Handler}};

{{- range $idv, $dv := .Dataviews}}


int {{$dv.Datasource_name -}}_{{- $dv.Datasource_channel -}}_callbacks::insert({{$dv.Handler -}}* env, const galois::gformat::pack_header_t& header,
    const typename {{$dv.Datasource_name -}}_{{- $dv.Datasource_channel -}}_etraits::update_t& data) {
    typename {{$dv.Datasource_name -}}_{{- $dv.Datasource_channel -}}_etraits::derivative_t derivative;

{{- range $icol, $col := .Columns}}

{{- if eq $col.Colume_from "derivative"}}
    std::remove_reference<decltype(derivative.{{- $col.Column_name -}}())>::type temp_{{- $col.Column_name -}};
    if (!{{- $dv.Get_udf -}}<int>::parse_{{- $col.Column_name -}}(data.{{- $col.Get_from -}}(), temp_{{- $col.Column_name -}})) {
        FATAL("Parse %s failed!", "{{- $col.Column_name -}}");
        return -1;
    } else {
       derivative.set_{{- $col.Column_name -}}(temp_{{- $col.Column_name -}});
    }
{{- end}}

{{- end}}
    return 0;
};

int {{$dv.Datasource_name -}}_{{- $dv.Datasource_channel -}}_callbacks::del({{$dv.Handler -}}* env, const galois::gformat::pack_header_t& header,
    const typename {{$dv.Datasource_name -}}_{{- $dv.Datasource_channel -}}_etraits::delete_t& data) {
    return 0;
};

int {{$dv.Datasource_name -}}_{{- $dv.Datasource_channel -}}_callbacks::update({{$dv.Handler -}}* env, const galois::gformat::pack_header_t& header,
    const typename {{$dv.Datasource_name -}}_{{- $dv.Datasource_channel -}}_etraits::update_t& data) {
    return 0;
};

{{end}}


}; // End of namespace