
/* 
This code is generated by gtable-generator, do not modify it. 
solopointer1202@gmail.com
*/
namespace {{.Namespace}} {

{{- range .Dataviews}}

typedef {{.Handler -}}* {{.Datasource_name -}}_{{- .Datasource_channel -}}_parse_env_t;
typedef {{.Handler -}}* {{.Datasource_name -}}_{{- .Datasource_channel -}}_update_env_t;
{{end}}
}; // End of namespace