#pragma once

/* 
This code is generated by gtable-generator, do not modify it. 
solopointer1202@gmail.com
*/

#include <exception>
#include "databus_datasource.h"
#include "loader.h"

{{- .Cppcode -}}

namespace {{.Namespace}} {
class {{.Handler}};

{{- range .Dataviews}}

typedef {{.Handler -}}* {{.Datasource_name -}}_{{- .Datasource_channel -}}_parse_env_t;
typedef {{.Handler -}}* {{.Datasource_name -}}_{{- .Datasource_channel -}}_update_env_t;
typedef galois::gdatabus::event_traits_t<{{- .Datasource_channel -}}> {{.Datasource_name -}}_{{- .Datasource_channel -}}_etraits;
class {{.Datasource_name -}}_{{- .Datasource_channel -}}_callbacks : public
    galois::gdatabus::schema_callbacks<
    {{.Datasource_name -}}_{{- .Datasource_channel -}}_parse_env_t,
    {{.Datasource_name -}}_{{- .Datasource_channel -}}_update_env_t,
    {{.Datasource_name -}}_{{- .Datasource_channel -}}_etraits
> {
public:
    static int insert({{.Handler -}}& env, const galois::gformat::pack_header_t& header,
        const typename {{.Datasource_name -}}_{{- .Datasource_channel -}}_etraits::update_t& data, uint32_t data_type) {
        return 0;
    };

    static int del({{.Handler -}}& env, const galois::gformat::pack_header_t& header,
        const typename {{.Datasource_name -}}_{{- .Datasource_channel -}}_etraits::delete_t& data, uint32_t data_type) {
        return 0;
    };

    static int update({{.Handler -}}& env, const galois::gformat::pack_header_t& header,
        const typename {{.Datasource_name -}}_{{- .Datasource_channel -}}_etraits::update_t& data, uint32_t data_type) {
        return 0;
    };
};

{{- end}}

class {{.Name -}}_schema : 
    public galois::gdatabus::default_traits<{{.Handler -}}*, {{.Handler -}}*> {
public:
{{- range .Dataviews}}
    typedef {{.Datasource_name -}}_{{- .Datasource_channel -}}_etraits {{.Datasource_channel -}};
    typedef {{.Datasource_name -}}_{{- .Datasource_channel -}}_callbacks {{.Datasource_channel -}}_callbacks;
{{end}}
};


typedef galois::gtable::databus_datasource<{{.Name -}}_schema> {{.Name -}}_source;

}; // End of namespace
